os:
- osx
language: node_js
node_js:
- node
- '8'
install:
- npm install
script:
- npm run build
- npm run publish2npm
branches:
  only:
  - master
deploy:
  provider: npm
  email: likai757@gmail.com
  on:
    tags: true
    all_branches: true
  api_key:
    secure: b/O8T+NuCEkGsKo192rQ4nAcPMRLAffDgILIuoz9V0Gpo9k0nidDguNKi2JcTnHeoej12Y6FZHcT9NGtoK2BZ/LamdpTw1ssS0BjHaDPhnpuSbZ+edUXSfbhoY+qtEAy2gvNuIz2IlyJ/bfkX15qq2ZoEsBzHEh9hX26/su9Jm2m7vxwlJfjklBDKa3dq9F93mn3hcUeddJyZypEHJ+RbiZHuHRQ9/eySzcudLaAfi7LwzaBpe869UP/5fdk/wt+QTVn3lBv0cDlVIZskKICVW3paLiV/ksERI/6m7GNheRamy/kHDcXWFkN9MJp5NjVVeFfpP+cdLrsz+vp6xEJJHegkRzfxurt8SLwnpYnlf+KkgeiUB5+CzBxVXGb9PARrlL28igsqdfIE9vuqkmDOBACXFa4y4LhxAIXq9HRnmiQeWhw8aTZdn4Z+JZTo7EXcHdsFViaEBAlRvwQh8HVkyvgBEcCIdPEJgpIwGsEssxYYwbsSFBDTFBso3uU+Qv86crWHTItnXreSf+BQ6iYbaIaRxvpgiksETYoAp6p6FHDPBcIT6mTIVK5METAfyHpa3XdLQViGIHq/zeFP5rgLOrkx/AxPC/3FrtdNwVS2Y/5peULlU6olC0H9PPPwkLd0hI0TUiPdsk0NToNubQOkbXHCBGmOZrncvOZkSewaO8=
